spring:
  application:
    name: 'greeting-service'
    
management:
  endpoints:
      exposure:
        include:
          - '*'    
    
greeting-service:
  greeting: 'Hello'
  default-value: 'World'    
  
 